server:
    port: 8280

logging:
  config: classpath:config/logback-spring.xml

spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  web:
    resources:
      cache:
        cachecontrol:
          max-age: 0
  security:
    user:
      name: admin
      password: change-me
